language: node_js
node_js:
    - "4"
    - "5"
    - "6"

addons:
    code_climate:
        repo_token: a4d2a58ead493d4e68de79c4e908e5fb53a8890301c58131807f4c3cc2ffdc9a

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info